
- platform: statistics
  name: Internet Test Down
  entity_id: sensor.speedtest_download
  state_characteristic: value_max
  max_age:
    days: 7
- platform: statistics
  name: Internet Test Up
  entity_id: sensor.speedtest_upload
  state_characteristic: value_max
  max_age:
    days: 7