both_date_and_time:
  name: Input with both date and time
  has_date: true
  has_time: true
only_date:
  name: Input with only date
  has_date: true
  has_time: false
outisde_light_delay:
  name: Outside Light Delay
  has_date: false
  has_time: true
announcement_delay:
  name: Announcement Delay
  has_date: false
  has_time: true
coffee_time:
  name: Coffee Time
  has_date: false
  has_time: true
good_morning:
  name: Good Morning
  has_date: false
  has_time: true
skylar_wakeup_call:
  name: Skylar Wakeup
  has_date: false
  has_time: true
christmas_show:
  name: Christmas Show
  has_date: false
  has_time: true
christmas_preshow:
  name: Christmas Preshow
  has_date: false
  has_time: true

good_night_routine:
  name: Good Night Routine
  has_date: false
  has_time: true
nightly_lockdown:
  name: Nightly Lockdown
  has_date: false
  has_time: true
morning_standby:
  name: Morning Standby
  has_date: false
  has_time: true

skylar_awake_at:
  name: Skylar Awake At
  has_date: false
  has_time: true